start = '2016-01-01'
end = '2019-12-30'
assets = ['ALUA.BA','CEPU.BA',
        'BBAR.BA','BMA.BA','CEPU',
        'COME.BA','CRES.BA','CVH.BA',
        'EDN.BA','GGAL.BA', 'LOMA.BA',
        'MIRG.BA', 'PAMP.BA', 'SUPV.BA',
        'TECO2.BA', 'TGNO4.BA', 'TGSU2.BA',
        'TRAN.BA', 'TXAR.BA', 'VALO.BA',
        'YPFD.BA']

asset_rava =['ALUA',
 'BBAR',
 'BMA',
 'CEPU',
 'COME',
 'CRES',
 'CVH',
 'EDN',
 'GGAL',
 'LOMA',
 'MIRG',
 'PAMP',
 'SUPV',
 'TECO2',
 'TGNO4',
 'TGSU2',
 'TRAN',
 'TXAR',
 'YPFD']